<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>accesser</AssemblyName>
    <RootNamespace>Accesser</RootNamespace>
    <Version>1.0.0</Version>
    <Description>A tool for solving SNI RST issues</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DnsClient" Version="1.7.0" />
    <PackageReference Include="Tomlyn" Version="0.17.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Nager.PublicSuffix" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
